#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <sys/wait.h>
#include <dlfcn.h>
#include <libgen.h>
#include <sys/stat.h>

// --- Forward Declarations & Globals ---
static char* s_current_filename = NULL;
static int s_current_line_num = 0;

static void unquote_if_needed(char* str);
static void trim_whitespace(char *str);

// --- JSON & Makefile Helpers ---

// Converts a JSON array string like `"foo.c", "bar.c"` to a make-friendly `foo.c bar.c`
static void clean_json_array_string(char* str) {
    if (!str) return;
    char* writer = str;
    char* reader = str;
    while (*reader) {
        if (isspace((unsigned char)*reader) || *reader == ',' || *reader == '"') {
            reader++;
            continue;
        }
        while (*reader && *reader != '"' && *reader != ',') {
            *writer++ = *reader++;
        }
        if (*reader) {
             *writer++ = ' ';
        }
    }
    *writer = '\0';
    trim_whitespace(str);
}

// Finds the value for a given key in a JSON string. Caller must free the result.
static char* find_json_value(const char* json_content, const char* key) {
    char key_pattern[256];
    snprintf(key_pattern, sizeof(key_pattern), "\"%s\":", key);
    const char* key_pos = strstr(json_content, key_pattern);
    if (!key_pos) return NULL;
    const char* value_start = key_pos + strlen(key_pattern);
    while (*value_start && isspace((unsigned char)*value_start)) value_start++;
    if (!*value_start) return NULL;
    const char* value_end;
    int is_array = 0;
    if (*value_start == '"') { value_start++; value_end = strchr(value_start, '"');
    } else if (*value_start == '[') { value_start++; value_end = strchr(value_start, ']'); is_array = 1;
    } else { value_end = value_start; while (*value_end && *value_end != ',' && *value_end != '}' && !isspace((unsigned char)*value_end)) value_end++; }
    if (!value_end) return NULL;
    size_t len = value_end - value_start;
    char* value = malloc(len + 1);
    if (!value) return NULL;
    memcpy(value, value_start, len);
    value[len] = '\0';
    if (is_array) { clean_json_array_string(value); } else { trim_whitespace(value); }
    return value;
}

// Converts a space-separated dependency list to proper linker flags.
static char* generate_linker_flags(char* deps_str) {
    if (!deps_str || !*deps_str) return strdup("");
    size_t max_len = strlen(deps_str) * 4 + 1;
    char* result = (char*)malloc(max_len);
    if (!result) return strdup("");
    result[0] = '\0';
    char* token = strtok(deps_str, " ");
    while (token) {
        if (strchr(token, '/') || strstr(token, ".a") || strstr(token, ".so")) {
            strcat(result, token);
        } else {
            strcat(result, "-l");
            strcat(result, token);
        }
        strcat(result, " ");
        token = strtok(NULL, " ");
    }
    return result;
}

// --- Makefile Generator ---
static void generate_makefile_from_config(const char* config_filename, FILE* out_fp) {
    FILE* fp = fopen(config_filename, "rb");
    if (!fp) { perror("Could not open config file"); return; }
    fseek(fp, 0, SEEK_END); long fsize = ftell(fp); fseek(fp, 0, SEEK_SET);
    char* json_content = malloc(fsize + 1);
    fread(json_content, 1, fsize, fp); fclose(fp); json_content[fsize] = '\0';

    char* target_name_full = strdup(config_filename);
    char* dot = strrchr(target_name_full, '.');
    if (dot) *dot = '\0';
    char* target_name = basename(target_name_full);

    char* p_srcdir = find_json_value(json_content, "srcdir");
    char* p_srcs = find_json_value(json_content, "src");
    char* p_cc = find_json_value(json_content, "cc");
    char* p_cflags = find_json_value(json_content, "cflags");
    char* p_ldflags = find_json_value(json_content, "ldflags");
    char* p_deps = find_json_value(json_content, "deps");
    char* p_dev_deps = find_json_value(json_content, "dev-deps");
    char* p_outdir = find_json_value(json_content, "outdir");

    char* deps_ldflags = generate_linker_flags(p_deps);
    char* dev_deps_ldflags = generate_linker_flags(p_dev_deps);

    fprintf(out_fp, "# Generated by metac from %s\n\n", config_filename);
    fprintf(out_fp, "# --- Core Configuration ---\n");
    fprintf(out_fp, "TARGET = %s\n", target_name);
    fprintf(out_fp, "CC = %s\n", p_cc ? p_cc : "cc");
    fprintf(out_fp, "OUTDIR = %s\n", p_outdir ? p_outdir : "build");
    fprintf(out_fp, "METAC_TOOL = ./metac\n\n");
    fprintf(out_fp, "# --- Flags ---\n");
    fprintf(out_fp, "CFLAGS = %s\n", p_cflags ? p_cflags : "");
    fprintf(out_fp, "LDFLAGS = %s\n", p_ldflags ? p_ldflags : "");
    fprintf(out_fp, "DEPS_LDFLAGS = %s\n", deps_ldflags);
    fprintf(out_fp, "DEV_DEPS_LDFLAGS = %s\n\n", dev_deps_ldflags);
    fprintf(out_fp, "# --- Source File Configuration ---\n");
    fprintf(out_fp, "SRCDIR = %s\n", p_srcdir ? p_srcdir : ".");
    fprintf(out_fp, "VPATH = $(SRCDIR)\n");
    fprintf(out_fp, "SRC_FILES = %s\n\n", p_srcs ? p_srcs : "");
    fprintf(out_fp, "# --- Automatic File Lists ---\n");
    fprintf(out_fp, "PREPROC_FILES = $(patsubst %%.c,$(OUTDIR)/%%.i,$(SRC_FILES))\n");
    fprintf(out_fp, "GEN_FILES = $(patsubst %%.c,$(OUTDIR)/%%.gen.c,$(SRC_FILES))\n");
    fprintf(out_fp, "OBJ_FILES = $(patsubst %%.c,$(OUTDIR)/%%.final.o,$(SRC_FILES))\n");
    fprintf(out_fp, "METAC_LIB = $(OUTDIR)/metac_lib.so\n\n");
    fprintf(out_fp, ".PHONY: all clean\n.SUFFIXES:\n\nall: $(OUTDIR)/$(TARGET)\n\n");
    fprintf(out_fp, "# 1. Final Link: Links all final objects into the executable with runtime dependencies.\n");
    fprintf(out_fp, "$(OUTDIR)/$(TARGET): $(OBJ_FILES)\n");
    fprintf(out_fp, "\t@echo \"[LD] $@\"\n");
    fprintf(out_fp, "\t$(CC) -o $@ $^ $(LDFLAGS) $(DEPS_LDFLAGS)\n\n");
    fprintf(out_fp, "# 2. Final Compile\n");
    fprintf(out_fp, "$(OUTDIR)/%%.final.o: $(OUTDIR)/%%.final.c -D\\$$COMPTIME_ERASE\n");
    fprintf(out_fp, "\t@echo \"[CC] $<\"\n");
    fprintf(out_fp, "\t$(CC) $(CFLAGS) -c -o $@ $<\n\n");
    fprintf(out_fp, "# 3. Metac Apply: Creates a .final.c file from a preprocessed source and the meta-library.\n");
    fprintf(out_fp, "$(OUTDIR)/%%.final.c: $(OUTDIR)/%%.i $(METAC_LIB)\n");
    fprintf(out_fp, "\t@echo \"[METAC-APPLY] $< -> $@\"\n");
    fprintf(out_fp, "\t$(METAC_TOOL) --apply $(METAC_LIB) $< -o $@\n\n");
    fprintf(out_fp, "# 4. Meta-Library Build: Links all generated code with metaprogramming dependencies.\n");
    fprintf(out_fp, "$(METAC_LIB): $(GEN_FILES)\n");
    fprintf(out_fp, "\t@echo \"[LIB] $@\"\n");
    fprintf(out_fp, "\t$(CC) $(CFLAGS) -fPIC -shared -o $@ $^ $(DEV_DEPS_LDFLAGS)\n\n");
    fprintf(out_fp, "# 5. Metac Generate: Creates a .gen.c file from a preprocessed source file.\n");
    fprintf(out_fp, "$(OUTDIR)/%%.gen.c: $(OUTDIR)/%%.i\n");
    fprintf(out_fp, "\t@echo \"[METAC-GEN] $< -> $@\"\n");
    fprintf(out_fp, "\t$(METAC_TOOL) $< -o $@\n\n");
    fprintf(out_fp, "# 6. C Preprocess: Creates a .i file from an original .c source.\n");
    fprintf(out_fp, "$(OUTDIR)/%%.i: %%.c\n");
    fprintf(out_fp, "\t@echo \"[CPP] $< -> $@\"\n");
    fprintf(out_fp, "\t@mkdir -p $(@D)\n");
    fprintf(out_fp, "\t$(CC) -E $(CFLAGS) $< -o $@ -D\\$$COMPTIME_ERASE\n\n");
    fprintf(out_fp, "# --- Cleanup Rule ---\n");
    fprintf(out_fp, "clean:\n");
    fprintf(out_fp, "\t@echo \"[CLEAN]\"\n");
    fprintf(out_fp, "\trm -rf $(OUTDIR) $(TARGET)\n");

    free(target_name_full); free(p_srcdir); free(p_srcs); free(p_cc);
    free(p_cflags); free(p_ldflags); free(p_deps); free(p_dev_deps);
    free(p_outdir); free(deps_ldflags); free(dev_deps_ldflags);
    free(json_content);
}

// --- Common Type Definitions ---
typedef struct { const char* ptr; size_t len; } StringView;
typedef StringView (*GeneratorFunc)();

// --- Hashing and String Utils ---
static unsigned long hash_string(const char *str) { unsigned long hash = 5381; int c; while ((c = *str++)) { hash = ((hash << 5) + hash) + c; } return hash; }
static void trim_whitespace(char *str) { if (!str || !*str) return; char *start = str; while (isspace((unsigned char)*start)) start++; char *end = start + strlen(start) - 1; while (end > start && isspace((unsigned char)*end)) end--; *(end + 1) = '\0'; if (start > str) memmove(str, start, end - start + 2); }
static char* escape_string_for_c(const char* str) { size_t new_len = 0; for (const char* p = str; *p; p++) { if (*p == '\\' || *p == '"' || *p == '\n' || *p == '\t' || *p == '\r') { new_len += 2; } else { new_len += 1; } } char* escaped = malloc(new_len + 1); if (!escaped) { perror("malloc"); return NULL; } char* out = escaped; for (const char* p = str; *p; p++) { switch (*p) { case '\\': *out++ = '\\'; *out++ = '\\'; break; case '"': *out++ = '\\'; *out++ = '"'; break; case '\n': *out++ = '\\'; *out++ = 'n'; break; case '\t': *out++ = '\\'; *out++ = 't'; break; case '\r': *out++ = '\\'; *out++ = 'r'; break; default: *out++ = *p; break; } } *out = '\0'; return escaped; }
static char* sanitize_type_for_identifier(const char* type) { size_t len = strlen(type); char* sanitized = malloc(len * 4 + 1); if (!sanitized) { perror("malloc"); return NULL; } char* writer = sanitized; for (const char* reader = type; *reader; ++reader) { if (isalnum((unsigned char)*reader)) { *writer++ = *reader; } else if (*reader == '*') { if (writer > sanitized && *(writer - 1) != '_') *writer++ = '_'; memcpy(writer, "ptr", 3); writer += 3; } else { if (writer > sanitized && *(writer - 1) != '_') { *writer++ = '_'; } } } *writer = '\0'; if (writer > sanitized && *(writer - 1) == '_') { *(writer - 1) = '\0'; } return sanitized; }

// --- Context-Aware Argument Extractor ---
typedef enum { STATE_NORMAL, STATE_IN_STRING, STATE_IN_CHAR, STATE_IN_BLOCK_COMMENT, STATE_IN_LINE_COMMENT } ParseState;
static const char* extract_arguments(const char *start, int num_args, char *args[]) { const char *p = start; if (*p != '(') return NULL; p++; for (int i = 0; i < num_args; ++i) args[i] = NULL; int paren_level = 1, arg_index = 0; const char* arg_start = p; ParseState state = STATE_NORMAL; while (*p && paren_level > 0) { switch (state) { case STATE_NORMAL: if (*p == '"') state = STATE_IN_STRING; else if (*p == '\'') state = STATE_IN_CHAR; else if (*p == '/' && *(p + 1) == '/') state = STATE_IN_LINE_COMMENT; else if (*p == '/' && *(p + 1) == '*') state = STATE_IN_BLOCK_COMMENT; break; case STATE_IN_STRING: if (*p == '"') state = STATE_NORMAL; else if (*p == '\\') p++; break; case STATE_IN_CHAR: if (*p == '\'') state = STATE_NORMAL; else if (*p == '\\') p++; break; case STATE_IN_BLOCK_COMMENT: if (*p == '*' && *(p + 1) == '/') state = STATE_NORMAL; break; case STATE_IN_LINE_COMMENT: if (*p == '\n') state = STATE_NORMAL; break; } if (state == STATE_NORMAL) { if (*p == '(') paren_level++; else if (*p == ')') paren_level--; else if (*p == ',' && paren_level == 1) { size_t len = p - arg_start; args[arg_index] = malloc(len + 1); if (!args[arg_index]) goto fail; memcpy(args[arg_index], arg_start, len); args[arg_index][len] = '\0'; trim_whitespace(args[arg_index]); arg_index++; arg_start = p + 1; } } if (*p == '\0') break; p++; } if (paren_level != 0) goto fail; size_t len = (p - 1) - arg_start; args[arg_index] = malloc(len + 1); if (!args[arg_index]) goto fail; memcpy(args[arg_index], arg_start, len); args[arg_index][len] = '\0'; trim_whitespace(args[arg_index]); if (arg_index + 1 != num_args) goto fail; return p; fail: for (int i = 0; i < num_args; ++i) free(args[i]); return NULL; }

// --- File Generation & #line Parsing ---
static void write_gen_header(FILE* out_fp, const char* content) {
    fprintf(out_fp, "// Generated by metac preprocessor. DO NOT EDIT.\n");
    //fprintf(out_fp, "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\n");
    fprintf(out_fp, "#define $COMPTIME\n\n");
    fprintf(out_fp, "#include <metac/comptime.h>\n");
    fprintf(out_fp, "%s", content); // Embed the preprocessed source
}
static void ensure_eval_helpers(FILE* out_fp, int* generated_flag) { 
    if (*generated_flag) return; 
    fprintf(out_fp, "// --- Default runtime serializers ---\n"); 
    const char* helpers = 
        "extern StringView _metac_serialize_int(int v);\n"
        "extern StringView _metac_serialize_long(long v);\n"
        "extern StringView _metac_serialize_float(float v);\n"
        "extern StringView _metac_serialize_double(double v);\n"
        "extern StringView _metac_serialize_const_char_ptr(const char* v);\n" 
        "extern StringView _metac_exec_eval(const char* filename, int line_num, const char* cmd);\n"
        "extern StringView _metac_exec_emit(const char* filename, int line_num, const char* cmd);\n"
        "extern StringView _metac_strcpy(const void* src, size_t count);\n\n";
        fprintf(out_fp, "%s", helpers); *generated_flag = 1;
    }

// Parses a #line directive and updates global state. Returns pointer after the directive.
static const char* parse_line_directive(const char* cursor) {
    const char* p = cursor + 5; // Skip "#line"
    while (*p && isspace((unsigned char)*p)) p++;
    s_current_line_num = atoi(p) - 1; // Subtract 1 because loop will increment on newline
    while (*p && isdigit((unsigned char)*p)) p++;
    while (*p && isspace((unsigned char)*p)) p++;
    if (*p == '"') {
        p++;
        const char* end_quote = strchr(p, '"');
        if (end_quote) {
            size_t len = end_quote - p;
            free(s_current_filename);
            s_current_filename = malloc(len + 1);
            memcpy(s_current_filename, p, len);
            s_current_filename[len] = '\0';
            p = end_quote + 1;
        }
    }
    while (*p && *p != '\n') p++;
    return p;
}

// --- Macro Handlers ---
static void handle_eval(FILE *out_fp, const char* filename, int line_num, const char* type, const char* expr, int* helper_flag) {
    ensure_eval_helpers(out_fp, helper_flag);
    char* sanitized_type = sanitize_type_for_identifier(type);
    if (!sanitized_type) return;
    char hash_input[4096]; 
    snprintf(hash_input, sizeof(hash_input), "%s:%d:$eval:%s", filename, line_num, expr); 
    unsigned long hash = hash_string(hash_input); 
    fprintf(out_fp, 
        "\n"
        "// Generated from: %s:%d for $eval\n"
        "StringView generate_eval_%lu() {\n"
        "#line %d \"%s\"\n"
        "    %s tmp = (%s);\n"
        "    return _metac_serialize_%s(tmp);\n"
        "}\n", 
        filename, line_num, hash, line_num, filename, type, expr, sanitized_type);
    free(sanitized_type);
}

static void handle_emit(FILE *out_fp, const char* filename, int line_num, const char* stmt) {
    char* escaped_stmt = escape_string_for_c(stmt);
    char hash_input[4096];
    snprintf(hash_input, sizeof(hash_input), "%s:%d:$emit:%s", filename, line_num, stmt);
    unsigned long hash = hash_string(hash_input);
    fprintf(out_fp, 
        "\n"
        "// Generated from: %s:%d for $emit\n"
        "StringView generate_emit_%lu() {\n"
        "    #line %d \"%s\"\n"
        "    static const char content[] = \"%s\";\n"
        "    return (StringView){.ptr = content, .len = sizeof(content) - 1};\n"
        "}\n", 
        filename, line_num, hash, line_num, filename, escaped_stmt);
    free(escaped_stmt);
}

static void handle_exec_eval(FILE* out_fp, const char* filename, int line_num, const char* type, const char* cmd, int* helper_flag) { 
    ensure_eval_helpers(out_fp, helper_flag);
    char* escaped_filename = escape_string_for_c(filename);
    char* sanitized_type = sanitize_type_for_identifier(type);
    if (!sanitized_type) return;
    char hash_input[4096]; 
    snprintf(hash_input, sizeof(hash_input), "%s:%d:$exec_eval:%s", filename, line_num, cmd); 
    unsigned long hash = hash_string(hash_input); 
    fprintf(out_fp, 
        "\n"
        "// Generated from: %s:%d for $exec_eval\n"
        "StringView generate_exec_eval_%lu() {\n"
        "#line %d \"%s\"\n"
        "    return _metac_exec_eval(\"%s\",%d,%s);\n"  //TODO check value compatibility with the return type?
        "}\n", 
        filename, line_num, hash, line_num, filename,  escaped_filename, line_num, cmd);
    free(sanitized_type);
    free(escaped_filename);
}

static void handle_exec_emit(FILE* out_fp, const char* filename, int line_num, const char* cmd) {
    char* escaped_filename = escape_string_for_c(filename);
    char hash_input[4096];
    snprintf(hash_input, sizeof(hash_input), "%s:%d:$exec_emit:%s", filename, line_num, cmd);
    unsigned long hash = hash_string(hash_input);
    fprintf(out_fp, 
        "\n"
        "// Generated from: %s:%d for $exec_emit\n"
        "StringView generate_exec_emit_%lu() {\n"
        "#line %d \"%s\"\n"
        "    return _metac_exec_emit(\"%s\",%d,%s);\n"
        "}\n", 
        filename, line_num, hash, line_num, filename,  escaped_filename, line_num, cmd);
    free(escaped_filename);
}

// --- Processing Drivers with #line support ---
void process_file_for_generation(const char *in_filename, const char *content, FILE *out_fp) {
    int eval_helpers_generated = 0;
    write_gen_header(out_fp, content);
    
    fprintf(out_fp, "\n#ifdef $COMPTIME\n"); 

    s_current_filename = strdup(in_filename);
    s_current_line_num = 1;
    const char* cursor = content;

    while (*cursor) {
        const char *p_line = strstr(cursor, "#line");
        const char *p_eval = strstr(cursor, "$eval(");
        const char *p_emit = strstr(cursor, "$emit(");
        const char *p_exec_eval = strstr(cursor, "$exec_eval(");
        const char *p_exec_emit = strstr(cursor, "$exec_emit(");

        const char *next_match = NULL;
        if (p_line) next_match = p_line;
        if (p_eval && (!next_match || p_eval < next_match)) next_match = p_eval;
        if (p_emit && (!next_match || p_emit < next_match)) next_match = p_emit;
        if (p_exec_eval && (!next_match || p_exec_eval < next_match)) next_match = p_exec_eval;
        if (p_exec_emit && (!next_match || p_exec_emit < next_match)) next_match = p_exec_emit;
        
        if (!next_match) break;

        for (const char* l = cursor; l < next_match; ++l) if (*l == '\n') s_current_line_num++;
        cursor = next_match;
        
        if (cursor == p_line) {
            cursor = parse_line_directive(cursor);
            if (*cursor == '\n') { s_current_line_num++; cursor++; }
        } else {
            const char* pattern_str = NULL; int num_args = 0;
            if (cursor == p_eval) { pattern_str = "$eval"; num_args = 2; }
            else if (cursor == p_emit) { pattern_str = "$emit"; num_args = 1; }
            else if (cursor == p_exec_eval) { pattern_str = "$exec_eval"; num_args = 2; }
            else { pattern_str = "$exec_emit"; num_args = 1; }
            
            char *args[2] = {NULL, NULL};
            const char *end = extract_arguments(cursor + strlen(pattern_str), num_args, args);
            if (end) {
                if (strcmp(pattern_str, "$eval") == 0) handle_eval(out_fp, s_current_filename, s_current_line_num, args[0], args[1], &eval_helpers_generated);
                else if (strcmp(pattern_str, "$emit") == 0) handle_emit(out_fp, s_current_filename, s_current_line_num, args[0]);
                else if (strcmp(pattern_str, "$exec_eval") == 0) handle_exec_eval(out_fp, s_current_filename, s_current_line_num, args[0], args[1], &eval_helpers_generated);
                else if (strcmp(pattern_str, "$exec_emit") == 0) handle_exec_emit(out_fp, s_current_filename, s_current_line_num, args[0]);
                cursor = end;
            } else { cursor++; }
            for (int i = 0; i < num_args; ++i) free(args[i]);
        }
    }

    fprintf(out_fp, "\n#endif\n"); 

    free(s_current_filename); s_current_filename = NULL;
}

void process_file_for_patching(const char *in_filename, const char *content, const char *lib_name, FILE *out_fp) {
    void* lib_handle = dlopen(lib_name, RTLD_LAZY);
    if (!lib_handle) { 
        fprintf(stderr, "Error: Could not open library '%s': %s\n", lib_name, dlerror()); 
        return;
    }

    s_current_filename = strdup(in_filename);
    s_current_line_num = 1;
    const char *cursor = content;

    while (*cursor) {
        const char *p_line = strstr(cursor, "#line");
        const char *p_eval = strstr(cursor, "$eval(");
        const char *p_emit = strstr(cursor, "$emit(");
        const char *p_exec_eval = strstr(cursor, "$exec_eval(");
        const char *p_exec_emit = strstr(cursor, "$exec_emit(");

        const char *next_match = NULL;
        if (p_line) next_match = p_line;
        if (p_eval && (!next_match || p_eval < next_match)) next_match = p_eval;
        if (p_emit && (!next_match || p_emit < next_match)) next_match = p_emit;
        if (p_exec_eval && (!next_match || p_exec_eval < next_match)) next_match = p_exec_eval;
        if (p_exec_emit && (!next_match || p_exec_emit < next_match)) next_match = p_exec_emit;

        if (!next_match) { fprintf(out_fp, "%s", cursor); break; }

        for (const char* l = cursor; l < next_match; ++l) if (*l == '\n') s_current_line_num++;
        fwrite(cursor, 1, next_match - cursor, out_fp);
        cursor = next_match;

        if (cursor == p_line) {
            cursor = parse_line_directive(cursor);
            if (*cursor == '\n') { s_current_line_num++; cursor++; }
        } else {
            const char* pattern_str = NULL; const char* macro_prefix = NULL; int num_args = 0; int needs_free = 0;
            if (cursor == p_eval) { pattern_str = "$eval"; macro_prefix="eval"; num_args = 2; needs_free = 1; }
            else if (cursor == p_emit) { pattern_str = "$emit"; macro_prefix="emit"; num_args = 1; needs_free = 0; }
            else if (cursor == p_exec_eval) { pattern_str = "$exec_eval"; macro_prefix="exec_eval"; num_args = 2; needs_free = 1; }
            else { pattern_str = "$exec_emit"; macro_prefix="exec_emit"; num_args = 1; needs_free = 0; }

            char *args[2] = {NULL, NULL};
            const char *end = extract_arguments(cursor + strlen(pattern_str), num_args, args);
            if (end) {
                char hash_input[4096];
                snprintf(hash_input, sizeof(hash_input), "%s:%d:%s:%s", s_current_filename, s_current_line_num, pattern_str, num_args == 1 ? args[0] : args[1]);
                unsigned long hash = hash_string(hash_input);
                char func_name[256];
                snprintf(func_name, sizeof(func_name), "generate_%s_%lu", macro_prefix, hash);
                dlerror();
                void* func_ptr = dlsym(lib_handle, func_name);
                const char* dlsym_error = dlerror();
                if (dlsym_error) {
                    fprintf(stderr, "Warning: Could not find symbol '%s' in lib '%s': %s\n", func_name, lib_name, dlsym_error);
                    fwrite(cursor, 1, end - cursor, out_fp);
                } else {
                    GeneratorFunc gen_func = (GeneratorFunc)func_ptr;
                    StringView result = gen_func();
                    fwrite(result.ptr, 1, result.len, out_fp);
                    if (needs_free && result.ptr) free((void*)result.ptr);
                }
                cursor = end;
            } else { fputc(*cursor, out_fp); cursor++; }
            for (int i = 0; i < num_args; ++i) free(args[i]);
        }
    }
    dlclose(lib_handle);
    free(s_current_filename); s_current_filename = NULL;
}

// --- Main Driver ---
int main(int argc, char *argv[]) {
    if (argc == 5 && strcmp(argv[1], "--gen-makefile") == 0 && strcmp(argv[3], "-o") == 0) {
        FILE *out_fp = fopen(argv[4], "w"); if (!out_fp) { perror("Makefile output"); return EXIT_FAILURE; }
        generate_makefile_from_config(argv[2], out_fp); fclose(out_fp);
        printf("Generated Makefile -> %s\n", argv[4]); return EXIT_SUCCESS;
    }
    if (argc == 6 && strcmp(argv[1], "--apply") == 0 && strcmp(argv[4], "-o") == 0) {
        FILE *in_fp = fopen(argv[3], "rb"); if (!in_fp) { perror(argv[3]); return EXIT_FAILURE; }
        fseek(in_fp, 0, SEEK_END); long fsize = ftell(in_fp); fseek(in_fp, 0, SEEK_SET);
        char *content = malloc(fsize + 1); fread(content, 1, fsize, in_fp); fclose(in_fp); content[fsize] = 0;
        FILE *out_fp = fopen(argv[5], "w"); if (!out_fp) { perror(argv[5]); free(content); return EXIT_FAILURE; }
        process_file_for_patching(argv[3], content, argv[2], out_fp);
        fclose(out_fp); free(content); return EXIT_SUCCESS;
    }
    if (argc == 4 && strcmp(argv[2], "-o") == 0) {
        FILE *in_fp = fopen(argv[1], "rb"); if (!in_fp) { perror(argv[1]); return EXIT_FAILURE; }
        fseek(in_fp, 0, SEEK_END); long fsize = ftell(in_fp); fseek(in_fp, 0, SEEK_SET);
        char *content = malloc(fsize + 1); fread(content, 1, fsize, in_fp); fclose(in_fp); content[fsize] = 0;
        FILE *out_fp = fopen(argv[3], "w"); if (!out_fp) { perror(argv[3]); free(content); return EXIT_FAILURE; }
        process_file_for_generation(argv[1], content, out_fp);
        fclose(out_fp); free(content); return EXIT_SUCCESS;
    }

    fprintf(stderr, "Usage:\n");
    fprintf(stderr, "  Generation:    %s <input.i> -o <output.gen.c>\n", argv[0]);
    fprintf(stderr, "  Apply:         %s --apply <lib.so> <input.i> -o <output.final.c>\n", argv[0]);
    fprintf(stderr, "  Makefile Gen:  %s --gen-makefile <config.json> -o <Makefile>\n", argv[0]);
    return EXIT_FAILURE;
}

// --- Supporting Helpers ---
static void unquote_if_needed(char* str) {
    if (!str) return;
    size_t len = strlen(str);
    if (len >= 2 && str[0] == '"' && str[len - 1] == '"'){
        memmove(str, str + 1, len - 2); str[len - 2] = '\0';
    }
}